### ISSUE TITLE
Show total hashrate pref in Tools menu

### ISSUE THREAD

**Issue by scar45** [cryptoGlance/cryptoGlance-web-app#39]
This needs to actually work to toggle the total hashrate(s) which appear just under the navbar. Also, switch/checkbox needs to be reworked per other areas to have a better 'target' area.

![image](https://cloud.githubusercontent.com/assets/262645/4086006/4e11edb4-2f2a-11e4-86dd-a77f51c3ab65.png)

**Comment by Stoyvo** [comment]
completed
