### ISSUE TITLE
update

### ISSUE THREAD

**Issue by CryptoCauseCoin** [cryptoGlance/cryptoGlance-web-app#44]
autoupdate not working. keeps halting on ==> Creating temporary directory to download update and unzip: update/v2.0
==> ERROR: Failed to create the directory: update/v2.0

**Comment by Stoyvo** [comment]
@CryptoCauseCoin what is the OS?

If it's linux, make sure the cryptoglance directory has write permissions 777 and the owner is the same as your httpd daemon. If you're using apache2, execute the permissionsfix.sh script: sudo sh permissionfix.sh
