### ISSUE TITLE
error popup at startup and at all refresh ...

### ISSUE THREAD

**Issue by pilere** [cryptoGlance/cryptoGlance-web-app#46]
HI,

since the last automatic update, I got this error from php-cgi : "il n'y a pas de disque dans le lecteur. Insérez un disque dans le lecteur \Device\Harddisk2\DR2" which will translate as : "The is no disk in the tray. Insert a disk in \Device\Harddisk2\DR2."

I did the upgrade by the automatic way, with nightly update ;)
I try to rename the web-cache folder with no success ... 
I also tried to erase the cookies with no success .... HELP 

I cannot use it anymore ...

Stéphane

**Comment by Stoyvo** [comment]
What is the OS? This looks like a Windows error, correct?

**Comment by pilere** [comment]
Le 11/05/2015 14:02, Stoyvo a écrit :
>
> What is the OS? This looks like a Windows error, correct?
>

yes windows 7, I tried to reinstall from scratch (with the user_data 
backup) but still got the error .... grrr

seems that it try to open something on F: ...

Stéphane

**Comment by Stoyvo** [comment]
@pilere Sorry Stéphane, A few things came up lately, was away from development for the past 2 weeks. Has this issue been resolved yet? I still cannot re-create this issue. I think it might be related to the "listen_on" value within C:\cryptoglance\settings.json. Please make sure it is set to:
"listen_on": ["127.0.0.1", 4041],

And that this port number is not in use. You can try to change the port number and see if that fixes the issue.

**Comment by pilere** [comment]
Hi, 
I didn't try since then and now it's working like a charm ... it did ask for an update but still before the update didn't show up with the popup ...
COOOL

Thanks for your help anyway !

Stéphane
